### ISSUE TITLE
login() fails with any user password combination.

### ISSUE THREAD

**Issue by Charrondev** [pouchdb-community/pouchdb-authentication#130] opened 2016-12-09 22:36 UTC
I am trying to sign in as the admin user I created. I want to avoid the window popup so I am passing in the Authorization header, and that seems to be working properly, but when I call the login function 

```
const user = {
      name: 'admin',
      password: 'password'
    }

    const pouchOpts = {
      skipSetup: true
    }

    const ajaxOpts = {
      ajax: {
        headers: {
          Authorization: 'Basic ' + window.btoa(user.name + ':' + user.password)
        }
      }
    }

    console.log(ajaxOpts)

    const db = new PouchDB(`http://localhost:5984/example`, pouchOpts)
    db.login(user.name, user.password, ajaxOpts).then((res) => {
    })
```

It throws an error saying that the authorization is invalid. It can't be invalid because it authorized access through the header, but it throws the following error on the server:

```
[error] [<0.135.0>] httpd 500 error response:
 {"error":"badmatch","reason":"{\"name\":\"admin\",\"password\":\"password\"}"}
```

I'm using CouchDB 1.6.1.

If I manually do the authorization using Postman, or an ajax library it seems to work properly though.

**Comment by Charrondev** [comment] 2016-12-12 00:54
So I've gotten it to work. The issue seems to be in `lib/index.js` when you JSON encode the username and password. ` body : JSON.stringify({name: username, password: password})`

If I pass options:

```
const ajaxOpts = {
  ajax: {
    headers: {
      Authorization: 'Basic ' + window.btoa('admin:password')
    },
    body: {
      name: 'admin',
      password: 'password'
    }
  }
}
```

into `login()` then it works properly, because it overrides whatever weird thing goes on in the json encoding. It's quite odd to be honest.

**Comment by quarthex** [comment] 2017-01-22 15:37
I made a [project](//github.com/quarthex/pouchdb-authentication-issue-130) that reproduce this issue.

**Comment by runchman** [comment] 2017-01-31 06:30
I also have this issue, with a caveat - it only fails when run on the server side, not the client side.

I've created a user in _user of username "guest", password "guest"

when I run db.login('guest','guest') on client side (chrome), works fine.
when I run db.login('guest','guest') within my node.js server code, I get the same error as in this thread.

Similar to Charrondev, the following ajax fixes the problem for me on the server code:

const ajaxOpts = {
    ajax: {
        body: {
            name: 'guest',
            password: 'guest'
        }
    }
}

**Comment by Charrondev** [comment] 2017-01-31 07:01
Sorry that I haven't been able to get into this recently, even though I opened the issue. If it works in the browser and not node, that makes sense for my situation, as I am using Electron, which straddles the line between the two.

**Comment by natcohen** [comment] 2017-02-21 20:36
Any chance we can get that working for Node.js? I'm having the same issue...

**Comment by ptitjes** [comment] 2017-11-20 06:04
Fixed by https://github.com/pouchdb-community/pouchdb-authentication/commit/5b61b004281e7b74adf2f19973f9c7edef75a702.

**Closed by ptitjes** 2017-11-20 06:04 UTC
Labels: bug, help wanted

**Comment by vogelbeere** [comment] 2017-11-27 11:25
The error I am getting is `Uncaught TypeError: this.remote.login is not a function` - is that the same error you were getting?

**Comment by ptitjes** [comment] 2017-11-27 12:15
@vogelbeere, no this is a different problem:
There is another problem with using `pouchdb-authentication` on Node.js, coming from a `pouchdb-ajax` bug. This bug have been fixed in `pouchdb`'s master branch (see https://github.com/pouchdb/pouchdb/issues/6814).

We are waiting for the next (coming soon) release of `pouchdb` to bump this dependency in `pouchdb-authentication`. Then you'll have a fully working stack in Node.js.

In the mean time, you can manually npm install `pouchdb-ajax/master` to your `node_modules`. But, if you want to do that in your `package.json`, you would have to do some `postinstall` script magic because `pouchdb` is a monorepo...

**Comment by vogelbeere** [comment] 2017-11-27 15:53
Thanks @ptitjes - I am not using Node though.

**Comment by ptitjes** [comment] 2017-11-27 16:10
Sorry, this issue is about some failures that happened with Node.js. So I thought this was you problem.

Would you mind opening another issue and explaining fully your problem, please ? (You'll see there is an issue template that guides you into what informations we need to help you solve your problem.)
Thank you.

**Comment by vogelbeere** [comment] 2017-11-27 16:45
Sorry - I am pretty sure that my issue is not caused by the code itself, but just wanted to know what error message this issue gave rise to. I have created a [StackOverflow question](https://stackoverflow.com/questions/47474384/couchdb-sync-access-on-google-app-engine).

**Comment by ptitjes** [comment] 2017-11-27 16:57
@vogelbeere If you had open an issue, that could have help others later. Also you are polluting an unrelated issue... Please, next time open an issue!

Anyway, I looked at your SO question (which I cannot answer because I don't have an SO account) and you are trying to call `login()` on a string (your `this.remote` is a string).
Hence the `TypeError: this.remote.login is not a function`. You should have done:
```this.remote = new PouchDB(remoteorigin + '/myPdb');```

**Comment by vogelbeere** [comment] 2017-11-27 17:05
Thanks!
