### ISSUE TITLE
Database has a global Failure - UnknownError: Error preparing Blob/File data to be stored in object store on iOS devices in non-private-mode

### ISSUE THREAD

**Issue by KevinK1507** [pouchdb-community/pouchdb-authentication#233] opened 2018-04-24 20:00 UTC
As you may now, ember-pouch doesn't work well in this moment with iOS devices. :
 [As described here](https://github.com/pouchdb/pouchdb/issues/7057)

everyone nows [this walkthrough of ember-simple-auth](https://github.com/simplabs/ember-simple-auth#walkthrough) will let us set up a simple login-form:

```
{{!-- app/templates/login.hbs --}}
<form {{action 'authenticate' on='submit'}}>
  <label for="identification">Login</label>
  {{input id='identification' placeholder='Enter Login' value=identification}}
  <label for="password">Password</label>
  {{input id='password' placeholder='Enter Password' type='password' value=password}}
  <button type="submit">Login</button>
  {{#if errorMessage}}
    <p>{{errorMessage}}</p>
  {{/if}}
</form>
```

which will call of course in pouchdb-authentification [as described here](https://github.com/pouchdb-community/pouchdb-authentication/blob/master/docs/recipes.md#everybody-has-to-be-logged-in-to-do-anything)

```
db.logIn('identification', 'password').then(function (batman) {
  console.log("I'm Batman.");
  return db.logOut();
});
```

and of course this will make this error:
[Image of Error](https://ibb.co/kqsOJc)

- important fix for that [on this link here](https://github.com/pouchdb/pouchdb/issues/7057)

Is there a way to include it asap ? Or will it not be implemented ? 

Of course at this moment, iPhone User can use private mode and everything is working, but that can't be a normal issue as everything should working on iOS 11.3 now as shown [here](https://demo.agektmr.com/storage/)

## Expected Behavior
Everthing is and should fine like on Android or especially in iOS Safari private mode yet

## Current Behavior
as you can see on that picture on top afterwards you login / connect to database
and after you want to create records:
[Image of Error II](https://ibb.co/hSw3jH)

## Possible Solution

https://github.com/pouchdb/pouchdb/issues/7057

## Update
May its not an pouchdb-authentification issue, but as I wrote that now, may this is still an information about that problem.

**Comment by ptitjes** [comment] 2018-04-25 09:50
Duplicate of pouchdb/pouchdb#7057. Closing.

**Closed by ptitjes** 2018-04-25 09:50 UTC
