### ISSUE TITLE
Authentication from local database PouchDB to remote database CouchDB

### ISSUE THREAD

**Issue by opaulet92** [pouchdb-community/pouchdb-authentication#121] opened 2016-09-21 08:03 UTC
Hello,

After looking for a lot in Web, I have nothing to answer to my question, that is : 

I have a local database (with `db = pouchDB('dbname')`). With this database, I would like to sync to a remote database CouchDB (with `db.sync('http://X.X.X.X:5984/dbname')`). If CouchDB has no user admin, all docs can be created to PouchDB and can be read. But if CouchDB has an user admin, when PouchDB will sync, I have a problem : 
```
{"error":"unauthorized", "reason":"Authentication required","status":"401","name":"aunauthorized"...}
```

For now, I understand I cannot use this plugin because you said : 

> But the pouchdb-authentication API will operate on your remote PouchDB object, not your local one.

About CouchDB, CORS properties are OK, and I have created an user admin (with username / password) and I works in CouchDB.

So, is it possible to authenticate it to CouchDB with this user admin to read docs and create it in local database PouchDB ? 

If you have any more information, tell me.
Thanks a lot.

**Comment by fasiha** [comment] 2016-09-28 00:22
Yes, I’ve done exactly this. I used Futon (http://127.0.0.1:5984/_utils/) to log into the remote database and PouchDB just used that authentication to sync.

**Comment by opaulet92** [comment] 2016-11-22 10:28
Hello,
I'm sorry but I don't understand what you said @fasiha. If you use Futon to log into the remote database, you cannot do this all time (production environment). 

I'm looking for the solution becase I have the same problem. How to auth when we sync a local PouchDB database with a remote CouchDB database ? Any solution ? 

Thanks.

**Comment by htrampe** [comment] 2016-12-23 12:54
Did u found a solution...?

**Comment by SinanGabel** [comment] 2016-12-23 13:36
Hi!

The below is taken directly from:

https://github.com/nolanlawson/pouchdb-authentication

Have you tried the db.login() function? Once this is working you can do
things like db.replicate(source, target, [options]), see more at pouchdb.com
.

var user = {
  name: 'admin',
  password: 'admin'
};
var pouchOpts = {
  skipSetup: true
};
var ajaxOpts = {
  ajax: {
    headers: {
      Authorization: 'Basic ' + window.btoa(user.name + ':' + user.password)
    }
  }
};
var db = new PouchDB('http://localhost:5984/test', pouchOpts);
db.login(user.name, user.password, ajaxOpts).then(function() {
  return db.allDocs();
}).then(function(docs) {
  console.log(docs);
}).catch(function(error) {
  console.error(error);
});

**Comment by promentol** [comment] 2017-09-06 19:06
I have fairly similar problem
I have **PouchDB** instance which is using local storage adapter, and is configured to sync to remote **CouchDB** database. The problem is, that `db.login` method is throwing error

> AuthError {status: 400, name: "authentication_error", message: "this plugin only works for the http/https adapter", 

How should we proceed?

**Comment by ptitjes** [comment] 2017-11-23 19:19
@opaulet92, @promentol, You have to log in on the remote database:
```js
var localDb = new PouchDB('mydatabase');
var remoteDb = new PouchDB('http://localhost:5984/mydatabase', {skip_setup: true});

remoteDb.login(username, password).then(function () {
  localDb.sync(remoteDb, {live: true, retry: true, /* other sync options */});
});
```

This issue is quite old, so I will close it. If you still have problems with that, please open a new issue.

**Closed by ptitjes** 2017-11-23 19:19 UTC

**Comment by ptitjes** [comment] 2018-04-06 05:42
MrGurns, we would need more informations. Please, do open a new issue and completely fill the issue template with the answers requested.

**Comment by MrGurns** [comment] 2018-04-06 16:20
Thanks. Posted it here: https://github.com/pouchdb-community/pouchdb-authentication/issues/231
