### ISSUE TITLE
Unable to handle 409 conflicts in the _users database

### ISSUE THREAD

**Issue by Blacktoviche** [pouchdb-community/pouchdb-authentication#140] opened 2017-03-01 23:28 UTC
I'm using pouchdb-authentication with PouchDB/CouchDB in ionic 2 project
when I tried (on purpose ) to signup with a name already exist 
I got this exception

```
VM12137 polyfills.js:3 PUT http://localhost:5984/_users/org.couchdb.user%3Amyname 409 (Conflict)
e @ VM12137 polyfills.js:3
t.scheduleTask @ VM12137 polyfills.js:3
e.scheduleMacroTask @ VM12137 polyfills.js:3
(anonymous) @ VM12137 polyfills.js:3
send @ VM13120:3
xhRequest @ VM12154 main.js:111682
ajax$1 @ VM12154 main.js:111701
ajaxCore @ VM12154 main.js:112235
ajax @ VM12154 main.js:112292
putUser @ VM12154 main.js:112338
(anonymous) @ VM12154 main.js:112366
(anonymous) @ VM12154 main.js:112654
t @ VM12137 polyfills.js:3
(anonymous) @ VM12154 main.js:112642
(anonymous) @ VM12154 main.js:112623
AuthProvicer.init @ VM12154 main.js:39765
Signup.onSignup @ VM12154 main.js:58669
View_Signup0.handleEvent_66 @ VM12332 component.ngfactory.js:895
(anonymous) @ VM12154 main.js:100585
(anonymous) @ VM12154 main.js:39347
t.invokeTask @ VM12137 polyfills.js:3
onInvokeTask @ VM12154 main.js:37395
t.invokeTask @ VM12137 polyfills.js:3
e.runTask @ VM12137 polyfills.js:3
invoke @ VM12137 polyfills.js:3
VM12154 main.js:54110 EXCEPTION: Uncaught (in promise): [object Object]
ErrorHandler.handleError @ VM12154 main.js:54110
IonicErrorHandler.handleError @ VM12154 main.js:110503
next @ VM12154 main.js:35094
schedulerFn @ VM12154 main.js:36604
SafeSubscriber.__tryOrUnsub @ VM12154 main.js:12767
SafeSubscriber.next @ VM12154 main.js:12716
Subscriber._next @ VM12154 main.js:12669
Subscriber.next @ VM12154 main.js:12633
Subject.next @ VM12154 main.js:14290
EventEmitter.emit @ VM12154 main.js:36596
NgZone.triggerError @ VM12154 main.js:37446
onHandleError @ VM12154 main.js:37425
t.handleError @ VM12137 polyfills.js:3
e.runGuarded @ VM12137 polyfills.js:3
r @ VM12137 polyfills.js:3
i @ VM12137 polyfills.js:3
invoke @ VM12137 polyfills.js:3
VM12154 main.js:54115 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ VM12154 main.js:54115
IonicErrorHandler.handleError @ VM12154 main.js:110503
next @ VM12154 main.js:35094
schedulerFn @ VM12154 main.js:36604
SafeSubscriber.__tryOrUnsub @ VM12154 main.js:12767
SafeSubscriber.next @ VM12154 main.js:12716
Subscriber._next @ VM12154 main.js:12669
Subscriber.next @ VM12154 main.js:12633
Subject.next @ VM12154 main.js:14290
EventEmitter.emit @ VM12154 main.js:36596
NgZone.triggerError @ VM12154 main.js:37446
onHandleError @ VM12154 main.js:37425
t.handleError @ VM12137 polyfills.js:3
e.runGuarded @ VM12137 polyfills.js:3
r @ VM12137 polyfills.js:3
i @ VM12137 polyfills.js:3
invoke @ VM12137 polyfills.js:3
VM12154 main.js:54116 Error: Uncaught (in promise): [object Object]
    at s (VM12137 polyfills.js:3)
    at s (VM12137 polyfills.js:3)
    at VM12137 polyfills.js:3
    at t.invokeTask (VM12137 polyfills.js:3)
    at Object.onInvokeTask (VM12154 main.js:37395)
    at t.invokeTask (VM12137 polyfills.js:3)
    at e.runTask (VM12137 polyfills.js:3)
    at i (VM12137 polyfills.js:3)
    at XMLHttpRequest.invoke (VM12137 polyfills.js:3)
```

**Comment by nolanlawson** [comment] 2017-03-03 16:33
This is normal; the _users database is a database like any other one and has conflicts that you have to deal with. Unfortunately this library doesn't really provide primitives to deal with cases like that; it is just a thin wrapper around CouchDB's existing authentication system.

Arguably we could add a new API to handle this, but I'm not sure what such an API would look like.

**Comment by ptitjes** [comment] 2017-11-23 22:04
@nolanlawson The documentation you wrote states that you might have an error with name `'conflict'` if there is already a user with that username (cf. [signUp](https://github.com/pouchdb-community/pouchdb-authentication#dbsignupusername-password--options--callback)). The op's exception is what is intended, right ? i.e. not a bug ?

I'm closing the issue. I'll reopen it if necessary.

**Closed by ptitjes** 2017-11-23 22:04 UTC
Labels: bug, help wanted
